import type { Metadata } from "next";
import { MarketingHeader } from "./_components/marketing-header";

export const metadata: Metadata = {
  title: "Calihub - Calisthenics companion",
  description: "Generated by create next app",
};

const MarketingLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <MarketingHeader />
      <main className="max-w-4xl w-full m-auto flex flex-col items-center">{children}</main>
    </>
  );
};

export default MarketingLayout;
