import type { Metadata } from 'next';
import { MarketingHeader } from './_components/marketing-header';
import { MarketingFooter } from './_components/marketing-footer';

export const metadata: Metadata = {
  title: 'Calihub - Calisthenics companion',
  description: 'Generated by create next app',
};

const MarketingLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className='h-full bg-neutral-300'>
      <MarketingHeader />
      <main className='m-auto flex w-full max-w-4xl flex-col items-center'>
        {children}
      </main>
      <MarketingFooter />
    </div>
  );
};

export default MarketingLayout;
